baseURL: "https://ryanbagley.com"
title: Ryan Bagley
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
canonifyURLs: true
languageCode: en-us
metaDataFormat: yaml
pygmentsUseClasses: false
summarylength: 40

minify:
    disableXML: true
    minifyOutput: false

params:
    font: 'Source Serif Pro'
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Ryan Bagley
    description: "The adventure blog of Ryan Bagley"
    keywords: [Adventure, Overland, Blog]
    author: Ryan Bagley
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: light
    disableThemeToggle: true
    ShowFullTextinRSS: true
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: false
    disableSpecial1stPost: false
    disableScrollToTop: true
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "/icons/favicon-32x32.png"
        favicon16x16: "/icons/favicon-16x16.png"
        favicon32x32: "/icons/favicon-32x32.png"
        apple_touch_icon: "/icons/icon-180x180.png"
        safari_pinned_tab: "/icons/favicon-16x16.png"

    label:
        text: "Ryan Bagley"
        #icon: /apple-touch-icon.png
        #iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hello."
        Content: "I'm Ryan Bagley, a network engineer 💻 and outdoor adventurer 🏃‍♂️ living in the American West. I enjoy sharing these adventures so that people other than my dogs 🐕‍🦺 can see the beauty of this peculiar geographic region. I also write about topics related to my hobbies and technical interests. You might see a few networking articles sneak in but I will try to mostly keep it easy like Sunday morning.  

If you enjoy thoughtful articles 📚 and some neat pictures from a guy running around in the wilderness 🏕️ then check out the archive or subscribe to my [RSS](https://ryanbagley.com/index.xml) feed."

    socialIcons:
        - name: "instagram"
          url: "https://www.instagram.com/tcp.rst/"
        - name: "telegram"
          url: "https://t.me/ryanbagley"
        - name: "email"
          url: "mailto:ryan@bagley.io"
        - name: "strava"
          url: "https://www.strava.com/athletes/ryanbagley"
        - name: "steam"
          url: "https://steamcommunity.com/profiles/76561197965221693"
        - name: "rss"
          url: "https://ryanbagley.com/index.xml"
        - name: "github"
          url: "https://github.com/steelcutoatmeal/ryanbagley.com"

    analytics:
        google:
            SiteVerificationTag: ""
        bing:
            SiteVerificationTag: ""
        yandex:
            SiteVerificationTag: ""

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page
        responsiveImages: false
        linkFullImages: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 10
        - identifier: about
          name: About
          url: /about/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary